Cts.Mvc.ExpenseReport/Cts.Mvc.ExpenseReport/Controllers/EntriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cts.Mvc.ExpenseReport.Domain;
using Cts.Mvc.ExpenseReport.DAL;

namespace Cts.Mvc.ExpenseReport.Controllers
{
    public class EntriesController : Controller
    {
        private ExpenseReportContext db = new ExpenseReportContext();

        public ViewResult Index()
        {

            ViewBag.EmployeesList = new SelectList(db.Employees, "EmployeesID", "FullName");
            //return View();
            //EntriesByEmployee(0, DateTime.Today, DateTime.Today);
            var entries = db.Entries.OrderBy(x => x.DateIncurred);
            //return View(db.Entries.AsEnumerable());
            return View(entries.AsEnumerable());
        }

        // GET: /Entries/Details/5
        [HttpGet]
        public ActionResult Details(int id = 0)
        {
            Entries entries = db.Entries.Find(id);
            if (entries == null)
            {
                return HttpNotFound();
            }
            return View(entries);
        }

        //
        // GET: /Entries/Create
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.EmployeesList = new SelectList(db.Employees, "EmployeesID", "FullName");
            ViewBag.ProjectsList = new SelectList(db.Projects, "ProjectsID", "Project");
            ViewBag.ExpenseCategoryList = new SelectList(db.ExpenseCategories, "ExpenseCategoriesID", "Category");
            ViewBag.BusinessReasonList = new SelectList(db.BusinessReasons, "BusinessReasonsID", "Reason");

            Entries entry = new Entries();
            entry.Mileage = 0;
            entry.Amount = 0;
            entry.NumPeople = 0;
            entry.DateIncurred = DateTime.Today;


            return View(entry);
        }

        //
        // POST: /Entries/Create
        [HttpPost]
        public ActionResult Create(Entries entries)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entries.Add(entries);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Unable to save changes.  Please try again.  If the problem persists, then contact your system administrator.");
            }

            return View(entries);
        }

        //
        // GET: /Entries/Edit/5
        [HttpGet]
        public ActionResult Edit(int id = 0)
        {
            Entries entries = db.Entries.Find(id);
            if (entries == null)
            {
                return HttpNotFound();
            }
            ViewBag.EmployeesList = new SelectList(db.Employees, "EmployeesID", "FullName", entries.EmployeesID);
            ViewBag.ProjectsList = new SelectList(db.Projects, "ProjectsID", "Project", entries.ProjectsID);
            ViewBag.ExpenseCategoryList = new SelectList(db.ExpenseCategories, "ExpenseCategoriesID", "Category", entries.ExpenseCategoriesID);
            ViewBag.BusinessReasonList = new SelectList(db.BusinessReasons, "BusinessReasonsID", "Reason", entries.BusinessReasonsID);

            return View(entries);
        }

        //
        // POST: /Entries/Edit/5
        [HttpPost]
        public ActionResult Edit(Entries entries)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(entries).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Unable to save changes.  Please try again.  If the problem persists, then contact your system administrator.");
            }

            return View(entries);
        }

        //
        // GET: /Entries/Delete/5
        [HttpGet]
        public ActionResult Delete(int id, bool? saveChangesError)
        {
            Entries entries = db.Entries.Find(id);
            //if (entries == null)
            //{
            //    return HttpNotFound();
            //}
            //return View(entries);
            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Unable to save changes. Please try again.  If the problem persists contact your system administrator";
            }

            return View(entries);
        }

        //
        // POST: /Entries/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //Entries entries = db.Entries.Find(id);
                    //db.Entries.Remove(entries);
                    Entries entry = new Entries() { EntriesID = id };
                    db.Entry(entry).State = EntityState.Deleted;
                    db.SaveChanges();
                }
            }
            catch (DataException)
            {
                return RedirectToAction("Delete",
                    new System.Web.Routing.RouteValueDictionary
                            {
                                {"id", id},
                                {"saveChangesError", true}
                            });
            }

            return RedirectToAction("Index");
        }

        public PartialViewResult EntriesByEmployee(DateTime? fromDate, DateTime? toDate, int id)
        {
            if (!fromDate.HasValue)
            {
                fromDate = Convert.ToDateTime("1/1/2000");
            }
            if (!toDate.HasValue)
            {
                toDate = Convert.ToDateTime("12/31/3000");
            }
            
            var m = db.Entries
                    .Where(x => x.EmployeesID == id && x.DateIncurred > fromDate && x.DateIncurred < toDate)
                    .OrderBy(r => r.DateIncurred)
                    .ThenBy(r => r.EntriesID)
                    .ToArray();
 
            return PartialView(m);
            
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Cts.Mvc.ExpenseReport/Cts.Mvc.ExpenseReport/Views/Entries/Create.cshtml
@model Cts.Mvc.ExpenseReport.Domain.Entries

@{
    ViewBag.Title = "Add Expense";
}

<h2>Add Expense</h2>

@using (Html.BeginForm())
{
    <div>
        @Html.Partial("_ValidationError")
    </div>

    <fieldset>
        <legend>Entries</legend>
        
        <div>
            @Html.Partial("_EntryDetails")
        </div> 
                
        <div>
            @Html.Partial("_SaveCancel")
        </div> 
    </fieldset>
}


@section Scripts {
    @Scripts.Render("~/bundles/fieldfunctions")
}

Cts.Mvc.ExpenseReport/Cts.Mvc.ExpenseReport/Views/Entries/Delete.cshtml
@model Cts.Mvc.ExpenseReport.Domain.Entries

@{
    ViewBag.Title = "Delete Entry";
}

<h2>Delete Entry</h2>

<h3>Are you sure you want to delete entry #@Html.DisplayFor(model => model.EntriesID)?</h3>
<fieldset>
<legend>Entries</legend>
@Html.HiddenFor(model => model.EntriesID, "EntriesID")

    <div class="row">
        <div class="span3">

            <div class="display-label">
                <b>@Html.DisplayNameFor(model => model.ProjectsID)</b>
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.Project.Project)
            </div>
            <br />
            <div class="display-label">
                <b>@Html.DisplayNameFor(model => model.ExpenseID)</b>
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.ExpenseID)
            </div>
            <br />
            <div class="display-label">
                <b>@Html.DisplayNameFor(model => model.NumPeople)</b>
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.NumPeople)
            </div>
            <br />
            <div class="display-label">
                <b>@Html.DisplayNameFor(model => model.Amount)</b>
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.Amount)
            </div>
            <br />
        </div>
        <div class="span3">
            <div class="display-label">
                <b>@Html.DisplayNameFor(model => model.ExpenseCategoriesID)</b>
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.Category.Category)
            </div>
            <br />

            <div class="display-label">
                <b>@Html.DisplayNameFor(model => model.DateIncurred)</b>
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.DateIncurred)
            </div>
            <br />

            <div class="display-label">
                <b>@Html.DisplayNameFor(model => model.Guests)</b>
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.Guests)
            </div>
            <br />

            <div class="display-label">
                <b>@Html.DisplayNameFor(model => model.Miles)</b>
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.Miles)
            </div>
        </div>
        <div class="span3">

            <div class="display-label">
                <b>@Html.DisplayNameFor(model => model.BusinessReasonsID)</b>
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.Reason.Reason)
            </div>
            <br />

            <div class="display-label">
                <b>@Html.DisplayNameFor(model => model.Vendor)</b>
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.Vendor)
            </div>
            <br />

            <div class="display-label">
                <b>@Html.DisplayNameFor(model => model.Affiliation)</b>
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.Affiliation)
            </div>
            <br />

            <div class="display-label">
                <b>@Html.DisplayNameFor(model => model.Mileage)</b>
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.Mileage)
            </div>
            <br />
        </div>
    </div>
</fieldset>
@using (Html.BeginForm())
{
    <div>
        <p>
            <button type="submit" value="Delete" class="btn btn-danger">Delete</button>
            <a href="@Url.Action("/Index")" role="button" class="btn btn-default">Cancel</a>
        </p>
    </div>
}

Cts.Mvc.ExpenseReport/Cts.Mvc.ExpenseReport/Views/Entries/Details.cshtml
@model Cts.Mvc.ExpenseReport.Domain.Entries

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Entries</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ExpenseID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ExpenseID)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DateIncurred)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateIncurred)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Guests)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Guests)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NumPeople)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NumPeople)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Affiliation)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Affiliation)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Vendor)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Vendor)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ProjectID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ProjectID)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ReasonID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ReasonID)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CategoryID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CategoryID)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Amount)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Amount)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Miles)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Miles)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Mileage)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Mileage)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.EntriesID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Cts.Mvc.ExpenseReport/Cts.Mvc.ExpenseReport/Views/Entries/Edit.cshtml
@model Cts.Mvc.ExpenseReport.Domain.Entries

@{
    ViewBag.Title = "Edit Expense";
}

<h2>Edit Expense</h2>

@using (Html.BeginForm())
{
    <div>
        @Html.Partial("_ValidationError")
    </div>

    <fieldset>
        <legend>Entries</legend>
        @Html.HiddenFor(model => model.EntriesID, "EntriesID")
        
        <div>
            @Html.Partial("_EntryDetails")
        </div> 
        
        <div>
            @Html.Partial("_SaveCancel")
        </div> 
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/fieldfunctions")
}

Cts.Mvc.ExpenseReport/Cts.Mvc.ExpenseReport/Views/Entries/EntriesByEmployee.cshtml
@model IEnumerable<Cts.Mvc.ExpenseReport.Domain.Entries>


<div class="row-fluid">
    <div class="span12">
        <table class="table table-striped table-condensed table-bordered table-hover info">
            <tr>
                <th width="2%"></th>
                <th>#</th>
                <th>Bill?</th>
                <th>Employee</th>
                <th>Date</th>
                <th>#People</th>
                <th>Guests</th>
                <th>Affiliation</th>
                <th>Vendor</th>
                <th>Project</th>
                <th>Reason</th>
                <th>Category</th>
                <th>Amount</th>
                <th>Miles</th>
                <th>Mileage</th>
                <th>Total</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <a href="@Url.Action("Delete", new { id = item.EntriesID })"><i class="icon-trash" title="Delete"></i></a>
                    </td>
                    <td>
                        <u><a href="@Url.Action("Edit", new { id = item.EntriesID })" >@Html.DisplayFor(modelItem => item.EntriesID) </a></u>
                    </td>
                    <td>@Html.DisplayFor(modelItem => item.Billable)</td>
                    <td>@Html.DisplayFor(modelItem => item.Employees.FullName)</td>
                    <td>@Html.DisplayFor(modelItem => item.DateIncurred)</td>
                    <td>@Html.DisplayFor(modelItem => item.NumPeople) </td>
                    <td>@Html.DisplayFor(modelItem => item.Guests)</td>
                    <td>@Html.DisplayFor(modelItem => item.Affiliation)</td>
                    <td>@Html.DisplayFor(modelItem => item.Vendor)</td>
                    <td>@Html.DisplayFor(modelItem => item.Project.Project)</td>
                    <td>@Html.DisplayFor(modelItem => item.Reason.Reason)</td>
                    <td>@Html.DisplayFor(modelItem => item.Category.Category)</td>
                    <td>@Html.DisplayFor(modelItem => item.Amount) </td>
                    <td>@Html.DisplayFor(modelItem => item.Miles)</td>
                    <td>@Html.DisplayFor(modelItem => item.Mileage)</td>
                    <td>@Html.DisplayFor(modelItem => item.Total)</td>

                </tr>
            }

        </table>
    </div>
</div>

Cts.Mvc.ExpenseReport/Cts.Mvc.ExpenseReport/Views/Entries/Index.cshtml
@model IEnumerable<Cts.Mvc.ExpenseReport.Domain.Entries>

@{
    ViewBag.Title = "Expenses";
}

<h2>Expenses</h2>

@using (Html.BeginForm("Index", "Entries", FormMethod.Post))
{ 
    <fieldset>
        <legend>Employees</legend>
        <div class="form-inline">
            @Html.DropDownList("EmployeesList", "Employee...")
            &nbsp;
            From: @Html.TextBox("DateFrom", "", new { @class = "datepicker", @readonly = "true", style = "width:100px" })
            &nbsp;
            To: @Html.TextBox("DateTo", "", new { @class = "datepicker", @readonly = "true", style = "width:100px" })
            &nbsp;
            <button type="button" class="btn btn-primary search" id="search">Search</button>
        </div>
        
        <br />
        <div class="row">
            <div class="span4">
                <div class="alert alert-error errorMessage" style="display: none">
                    <ul>
                        <b>
                            <li class="employeeError" style="display: none">
                                @Html.ValidationMessage("DateFrom", "Employee must be selected", new { style = "display:none", @class = "employeeError" })
                            </li>
                            <li class="dateError" style="display: none">
                                @Html.ValidationMessage("DateFrom", "From date must be before To date", new { style = "display:none", @class = "dateError" })
                            </li>
                        </b>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="span3">
                <div>
                    <a href="@Url.Action("Create")" role="button" class="btn btn-default">Create Expense</a>
                </div>
            </div>
        </div>
        <div id="target">
            @{ Html.RenderPartial("EntriesByEmployee");  }
        </div>
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/fieldfunctions")
}

Cts.Mvc.ExpenseReport/Cts.Mvc.ExpenseReport/Views/Entries/_EntryDetails.cshtml
@model Cts.Mvc.ExpenseReport.Domain.Entries


<div class="row">
    <div class="span12">
        <div class="span3">
            <div class="editor-label">
                @Html.LabelFor(model => model.EmployeesID)
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(p => p.EmployeesID, ViewBag.EmployeesList as SelectList, "Select Employee...")
                @Html.ValidationMessageFor(model => model.EmployeesID, "*")
            </div>
        </div>
        <div class="span3">
            <div class="editor-label">
                @Html.LabelFor(model => model.DateIncurred)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(m => m.DateIncurred, "{0:MM/dd/yyyy}", new { @class = "datepicker", @readonly = "true", style = "width:100px" })
                @Html.ValidationMessageFor(model => model.DateIncurred, "*")
            </div>
        </div>
        <div class="span3">
            <div class="editor-label">
                @Html.LabelFor(model => model.Billable)
            </div>
            <div class="editor-field">
                @Html.CheckBoxFor(model => model.Billable)
                @Html.ValidationMessageFor(model => model.ExpenseCategoriesID, "*")
            </div>
        </div>
    </div>
    <div class="span12">
        <div class="span3">
            <div class="editor-label">
                @Html.LabelFor(model => model.ProjectsID)
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(p => p.ProjectsID, ViewBag.ProjectsList as SelectList, "Select Project...")
                @Html.ValidationMessageFor(model => model.ProjectsID, "*")
            </div>
        </div>
        <div class="span3">
            <div class="editor-label">
                @Html.LabelFor(model => model.ExpenseCategoriesID)
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(e => e.ExpenseCategoriesID, ViewBag.ExpenseCategoryList as SelectList, "Select Category...")
                @Html.ValidationMessageFor(model => model.ExpenseCategoriesID, "*")
            </div>
        </div>
        <div class="span3">
            <div class="editor-label">
                @Html.LabelFor(model => model.BusinessReasonsID)
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(b => b.BusinessReasonsID, ViewBag.BusinessReasonList as SelectList, "Select Reason...")
                @Html.ValidationMessageFor(model => model.BusinessReasonsID, "*")
            </div>
        </div>
    </div>
    <div class="span12">
        <div class="span3">
            <div class="editor-label">
                @Html.LabelFor(model => model.ExpenseID)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.ExpenseID)
                @Html.ValidationMessageFor(model => model.ExpenseID, "*")
            </div>
        </div>
        <div class="span3">
            <div class="editor-label">
                @Html.LabelFor(model => model.Vendor)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Vendor)
                @Html.ValidationMessageFor(model => model.Vendor, "*")
            </div>
        </div>
        <div class="span3">
            <div class="editor-label">
                @Html.LabelFor(model => model.NumPeople)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.NumPeople)
                @Html.ValidationMessageFor(model => model.NumPeople, "*")
            </div>
        </div>
    </div>
    <div class="span12">
        <div class="span3">
            <div class="editor-label">
                @Html.LabelFor(model => model.Guests)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Guests)
                @Html.ValidationMessageFor(model => model.Guests, "*")
            </div>
        </div>
        <div class="span3">
            <div class="editor-label">
                @Html.LabelFor(model => model.Affiliation)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Affiliation)
                @Html.ValidationMessageFor(model => model.Affiliation, "*")
            </div>
        </div>
        <div class="span3">
            <div class="editor-label">
                @Html.LabelFor(model => model.Amount)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(model => model.Amount, "{0:C}", new { @class = "amount", @Value = "0.00" })
                @Html.ValidationMessageFor(model => model.Amount, "*")
            </div>
        </div>
    </div>
    <div class="span12">
        <div class="span3">
            <div class="editor-label">
                @Html.LabelFor(model => model.Miles)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(model => model.Miles, new { @class = "miles", @Value = "0" })
                @Html.ValidationMessageFor(model => model.Miles, "*")
            </div>
        </div>
        <div class="span3">
            <div class="editor-label">
                @Html.LabelFor(model => model.Mileage)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(model => model.Mileage, "{0:C}", new { @class = "mileage", @Value = "0.00" })
                @Html.ValidationMessageFor(model => model.Miles, "*")
            </div>
        </div>
        <div class="span3">
            <div class="editor-label">
                @Html.LabelFor(model => model.Total)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(model => model.Total, "{0:C}", new { @class = "total", @Value = "0.00" })
                @Html.ValidationMessageFor(model => model.Total, "*")
            </div>
        </div>
    </div>
</div>

Cts.Mvc.ExpenseReport/Cts.Mvc.ExpenseReport/Views/Entries/_SaveCancel.cshtml
@model Cts.Mvc.ExpenseReport.Domain.Entries

<p>
    <button type="submit" value="Save" class="btn btn-primary">Save</button>
    <a href="@Url.Action("/Index")" role="button" class="btn btn-default">Cancel</a>
</p>

Cts.Mvc.ExpenseReport/Cts.Mvc.ExpenseReport/Views/Entries/_ValidationError.cshtml
@model Cts.Mvc.ExpenseReport.Domain.Entries


<div class="row">
    <div class="span4 alert alert-error" id="validationSummary" style="display: none">
        @Html.ValidationSummary(false)
    </div>
</div>